# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 242e06506597d7935649cfd93ee1aa986c7b0d4a44ee1c8a695dd68d30a281e7ad416331c01a4df3e4ae476b0cb55a413a9e11770e51e1e91ef506e499199e4f

test:
  secret_key_base: 5303a1d27d5e7130e80158e2afc7df58c7c6ee83650feed88102a9d46441927706f2bec2ed9ce2fbd1ce026ab5e0bd19f76bc28b09194ec21dfda6147b682157

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
